### ISSUE TITLE
Build failing with "IsADirectoryError" with V0 for RPI3

### ISSUE THREAD

**Issue by sjthespian** [pikvm/pikvm#1135]
**Describe the bug**
When building an image for V0 on the RPI3, the os build succeeds, but the image build is failing with the following error:
```
IsADirectoryError: [Errno 21] Is a directory: './.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs/usr/share/licenses/common/RUBY'
```
This is a true statement, that is a directory containing just the license.txt file, as is everything else in that directory.

The build is being run on Ubuntu 22.04.3.

**To Reproduce**
Steps to reproduce the behavior, like:
1. Clone the pikvm repo
2. CD to the os directory
3. Create a config.mk file (BOARD = rpi3, PLATFORM = v0-hdmi, HOSTNAME = pikvm. LOCALE = en_US, TIMEZONE = America/Los_Angeles)
4. run `make os`
5. run `make image`

**Expected behavior**
The build should create an image in the images/ directory.

**Screenshots**
The tail end of the build showing the failure, stack trace, and error:
```
#
docker save --output=./.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs.tar pi-builder.pikvm-os.v0-hdmi.arch-rpi3-arm-result
docker run --rm --tty \
                --volume=/home/drich/Src/pikvm/os/.pi-builder/v0-hdmi-rpi3/./.cache:/root/./.cache --workdir=/root/./.cache/.. \
        pi-builder.pikvm-os.v0-hdmi.toolbox \
                /tools/docker-extract \
                        --remove-root \
                        --root=./.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs \
                        --set-hostname="pikvm" \
                        --remove-qemu \
                ./.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs.tar
:: Extracting rootfs to './.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs' ...
Traceback (most recent call last):
  File "/tools/docker-extract", line 182, in <module>
    main()
  File "/tools/docker-extract", line 161, in main
    _extract_rootfs(image_tar, _get_image_layers(image_tar), options.root)
  File "/tools/docker-extract", line 98, in _extract_rootfs
    layer_tar.extractall(
  File "/usr/lib/python3.11/tarfile.py", line 2264, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.11/tarfile.py", line 2331, in _extract_one
    self._handle_fatal_error(e)
  File "/usr/lib/python3.11/tarfile.py", line 2327, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.11/tarfile.py", line 2418, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/tools/docker-extract", line 120, in makelink
    self.__remove(targetpath)
  File "/tools/docker-extract", line 125, in __remove
    os.unlink(targetpath)
IsADirectoryError: [Errno 21] Is a directory: './.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs/usr/share/licenses/common/RUBY'
make[1]: *** [Makefile:286: extract] Error 1
make[1]: Leaving directory '/home/drich/Src/pikvm/os/.pi-builder/v0-hdmi-rpi3'
make: *** [Makefile:82: install] Error 2
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS, Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
 - Browser N/A
 - Version N/A
 - VNC client N/A

**PiKVM info:**
  - Raspberry Pi board version [e.g. RPi 4]: RPI 3
  - PiKVM platform v0-hdmi
  - Video capture type CSI bridge
  - KVMD version: N/A - not getting that far
  - uStreamer version: N/A - not getting that far
  - Linux kernel: From the build system: `Linux morpheus 5.15.0-86-generic #96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Additional context**
The full `make image` output:
```
❯ make image
zsh: correct 'image' to 'images' [nyae]? n
mkdir -p images
make -C ./.pi-builder/v0-hdmi-rpi3 image IMAGE=/home/drich/Src/pikvm/os/images/v0-hdmi-rpi3-20231016.img IMAGE_XZ=1
make[1]: Entering directory '/home/drich/Src/pikvm/os/.pi-builder/v0-hdmi-rpi3'
===== Ensuring toolbox image =====
make -C toolbox toolbox
make[2]: Entering directory '/home/drich/Src/pikvm/os/.pi-builder/v0-hdmi-rpi3/toolbox'
rm -f *.tgz Dockerfile
test -n "docker"
test -n "rpi3"
test -n "arm"
test -n "http://de3.mirror.archlinuxarm.org"
test -n "pi-builder.pikvm-os.v0-hdmi.toolbox"
test -n "x86_64"
test arm != x86_64 || ln ../base/arch-rpi3-arm.tgz .
sed -e 's|%BASE_ROOTFS_TGZ%|arch-rpi3-arm.tgz|g' Dockerfile.x86_64 > Dockerfile
cat Dockerfile.common >> Dockerfile
docker build \
                --rm \
                --tag pi-builder.pikvm-os.v0-hdmi.toolbox \
                --build-arg "REPO_URL=http://de3.mirror.archlinuxarm.org" \
                 \
        .
[+] Building 0.7s (13/13) FINISHED
 => [internal] load .dockerignore                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                               0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                          0.0s
 => => transferring dockerfile: 854B                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/archlinux/archlinux:base                                                                                                                           0.6s
 => [internal] load build context                                                                                                                                                             0.0s
 => => transferring context: 113B                                                                                                                                                             0.0s
 => [1/8] FROM docker.io/archlinux/archlinux:base@sha256:d65925894e72425f69eeea495e16631e3611f68e5b78ae820cf8b26b6d61057c                                                                     0.0s
 => CACHED [2/8] RUN mkdir -p /etc/pacman.d/hooks  && ln -s /dev/null /etc/pacman.d/hooks/30-systemd-tmpfiles.hook                                                                            0.0s
 => CACHED [3/8] RUN pacman --noconfirm --ask=4 -Syy  && pacman --needed --noconfirm --ask=4 -S   glibc   openssl   openssl-1.1  && pacman --needed --noconfirm --ask=4 -S   pacman  && pacm  0.0s
 => CACHED [4/8] RUN mkdir /tools                                                                                                                                                             0.0s
 => CACHED [5/8] COPY binfmt /tools/                                                                                                                                                          0.0s
 => CACHED [6/8] COPY docker-extract /tools/                                                                                                                                                  0.0s
 => CACHED [7/8] COPY disk /tools/                                                                                                                                                            0.0s
 => CACHED [8/8] COPY install /tools/                                                                                                                                                         0.0s
 => exporting to image                                                                                                                                                                        0.0s
 => => exporting layers                                                                                                                                                                       0.0s
 => => writing image sha256:8179cca7e424d5c006c6a287790e9970b114976f3660c994ae11c71340a05f65                                                                                                  0.0s
 => => naming to docker.io/library/pi-builder.pikvm-os.v0-hdmi.toolbox                                                                                                                        0.0s
make[2]: Leaving directory '/home/drich/Src/pikvm/os/.pi-builder/v0-hdmi-rpi3/toolbox'
===== Toolbox image is ready =====
===== Extracting image from Docker =====
test ! -d ./.cache || docker run --rm --tty --volume=/home/drich/Src/pikvm/os/.pi-builder/v0-hdmi-rpi3:/root/dir --workdir=/root/dir pi-builder.pikvm-os.v0-hdmi.toolbox rm -rf .cache
mkdir -p ./.cache
test -n "./.cache"
echo "Signature: 8a477f597d28d172789f06886806bc55" > "./.cache/CACHEDIR.TAG"
#
docker save --output=./.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs.tar pi-builder.pikvm-os.v0-hdmi.arch-rpi3-arm-result
docker run --rm --tty \
                --volume=/home/drich/Src/pikvm/os/.pi-builder/v0-hdmi-rpi3/./.cache:/root/./.cache --workdir=/root/./.cache/.. \
        pi-builder.pikvm-os.v0-hdmi.toolbox \
                /tools/docker-extract \
                        --remove-root \
                        --root=./.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs \
                        --set-hostname="pikvm" \
                        --remove-qemu \
                ./.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs.tar
:: Extracting rootfs to './.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs' ...
Traceback (most recent call last):
  File "/tools/docker-extract", line 182, in <module>
    main()
  File "/tools/docker-extract", line 161, in main
    _extract_rootfs(image_tar, _get_image_layers(image_tar), options.root)
  File "/tools/docker-extract", line 98, in _extract_rootfs
    layer_tar.extractall(
  File "/usr/lib/python3.11/tarfile.py", line 2264, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.11/tarfile.py", line 2331, in _extract_one
    self._handle_fatal_error(e)
  File "/usr/lib/python3.11/tarfile.py", line 2327, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.11/tarfile.py", line 2418, in _extract_member
    self.makelink(tarinfo, targetpath)
  File "/tools/docker-extract", line 120, in makelink
    self.__remove(targetpath)
  File "/tools/docker-extract", line 125, in __remove
    os.unlink(targetpath)
IsADirectoryError: [Errno 21] Is a directory: './.cache/pikvm-os.v0-hdmi.arch-rpi3-arm.rootfs/usr/share/licenses/common/RUBY'
make[1]: *** [Makefile:286: extract] Error 1
make[1]: Leaving directory '/home/drich/Src/pikvm/os/.pi-builder/v0-hdmi-rpi3'
make: *** [Makefile:89: image] Error 2
```

**Comment by mdevaev** [comment]
Hello. I can't reproduce it :/ Can I debug it on your machine using `tmate`?

**Comment by anton-tokarev-softeq** [comment]
+1 the same error

**Comment by mdevaev** [comment]
Found a bug, fixing...

**Comment by mdevaev** [comment]
Fixed. Please re-clone entire `os` buildenv.

**Comment by sjthespian** [comment]
Looks good, I just got a successfully image build! Thanks!!!

**Comment by mdevaev** [comment]
:ok_hand:
