### ISSUE TITLE
kvmd-pstrun exception

### ISSUE THREAD

**Issue by aastein** [pikvm/pikvm#776]
**Describe the bug**
Running `kvmd-pstrun -- true` results in the following exception

```
--    INFO -- Opening PST session ...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1378, in _create_connection
    _, proto = await self._loop.create_unix_connection(
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 254, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 505, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/kvmd-pstrun", line 9, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/kvmd/apps/pstrun/__init__.py", line 148, in main
    aiotools.run(_run_cmd(options.cmd, config.pst.server.unix))
  File "/usr/lib/python3.10/site-packages/kvmd/aiotools.py", line 154, in run
    loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/kvmd/apps/pstrun/__init__.py", line 130, in _run_cmd
    async with session.ws_connect("http://localhost:0/ws") as ws:
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect
    resp = await self.request(
  File "/usr/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/lib/python3.10/site-packages/aiohttp/connector.py", line 1382, in _create_connection
    raise UnixClientConnectorError(self.path, req.connection_key, exc) from exc
aiohttp.client_exceptions.UnixClientConnectorError: Cannot connect to unix socket /run/kvmd/pst.sock ssl:default [No such file or directory]
```

**To Reproduce**
* rw
* pacman -Syu
* reboot
* kvmd-pstrun -- true

**Expected behavior**
Should not cause exception

**PiKVM info:**
  - Raspberry Pi board version: unknown. pre-assembled model. 
  - KVMD version: 
  ```
kvmd 3.119-1
kvmd-fan 0.22-1
kvmd-oled 0.12-1
kvmd-platform-v3-hdmi-rpi4 3.119-1
kvmd-webterm 0.42-1
  ```
  - uStreamer version: ustreamer 5.13-1
  - Linux kernel: `Linux pikvm 5.15.34-4-rpi-ARCH #1 SMP Tue Jul 5 12:10:16 MSK 2022 armv7l GNU/Linux`

**Comment by mdevaev** [comment]
You have an old sd card image. PST requires a special partition to work. Reflash it and everything will be ok.
